version: '3.8'

services:
  # --- BACKEND SYMFONY ---
  backend:
    build:
      context: ./backend          # Contexto en directorio backend
      dockerfile: Dockerfile      # Dockerfile dentro de backend
    volumes:
      - ./backend:/var/www/html:delegated
    environment:
      DATABASE_URL: mysql://root:root@db:3306/pire_db
      APP_ENV: dev
    depends_on:
      - db

  # --- FRONTEND ESTÁTICO ---
  frontend:
    build:
      context: ./frontend         # Contexto en directorio frontend
      dockerfile: Dockerfile      # Dockerfile dentro de frontend
    volumes:
      - ./frontend:/usr/share/frontend:delegated
    ports:
      - '3000:3000'
    depends_on:
      - backend

  # --- NGINX COMO REVERSE PROXY ---
  nginx:
    image: nginx:alpine
    ports:
      - '8000:80'
    volumes:
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/public:/var/www/html/public:ro
      - ./frontend:/usr/share/frontend:ro
    depends_on:
      - backend
      - frontend

  # --- BASE DE DATOS MYSQL ---
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pire_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: