nelmio_cors:
    defaults:
        allow_origin: ['https://insightful-enchantment-production.up.railway.app']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        max_age: 3600
    paths:
        '^/api/':
            origin_regex: false
            allow_origin: ['https://insightful-enchantment-production.up.railway.app']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600
