# config/packages/security.yaml
security:
  # 1) Hashers para las contraseñas
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # 2) Proveedor de usuarios desde entidad
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # 3) Firewalls (el orden importa)
  firewalls:
    # a) Desactiva seguridad para el profiler y assets en dev
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # b) API REST JSON (stateless + json_login)
    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      # anonymous: true
      json_login:
        check_path: /api/login
        username_path: username
        password_path: password

    # c) Web tradicional con formularios
    main:
      pattern: ^/
      provider: app_user_provider
      lazy: true
      # anonymous: lazy
      form_login:
        login_path: app_login         # nombre de tu ruta de login web
        check_path: app_login
        enable_csrf: true
        default_target_path: app_main # ruta tras login web
        username_parameter: email
        password_parameter: password
        use_referer: true
      logout:
        path: app_logout
        target: app_main

  # 4) Control de acceso (solo la primera regla que coincida)
  access_control:
    - { path: ^/api/register, roles: PUBLIC_ACCESS }
    - { path: ^/api/login,    roles: PUBLIC_ACCESS }
    - { path: ^/api,          roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/login,        roles: PUBLIC_ACCESS }
    - { path: ^/register,     roles: PUBLIC_ACCESS }
    # - { path: ^/admin,      roles: ROLE_ADMIN }
    # - { path: ^/profile,    roles: ROLE_USER }

# 5) Overrides para tests (acelerar hashing)
when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
