# config/packages/security.yaml
security:
  # 1) Hashers para las contraseñas
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # 2) Proveedor de usuarios desde entidad
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # 3) Firewalls (el orden importa)
  firewalls:
    # a) Desactiva seguridad para el profiler y assets en dev
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # b) Login JSON para emitir el JWT
    login:
      pattern: ^/api/login
      stateless: true
      provider: app_user_provider
      json_login:
        check_path: /api/login
        username_path: username
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    # c) API REST protegida por JWT
    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~
      logout:
        path: /api/logout

    # d) Firewall para la web tradicional
    main:
      pattern: ^/(?!api)
      provider: app_user_provider
      lazy: true
      entry_point: form_login
      form_login:
        login_path: /login
        check_path: /login_check
      logout:
        path: /logout
        target: /login.html
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800 # 1 semana
        path: /

  # 4) Control de acceso (solo la primera regla que coincida)
  access_control:
    - { path: ^/api/login$,    roles: PUBLIC_ACCESS }
    - { path: ^/api/register,  roles: PUBLIC_ACCESS }
    - { path: ^/api,           roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api/users/me,  roles: IS_AUTHENTICATED_FULLY }

# 5) Overrides para tests (acelerar hashing)
when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
